name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-east1
  SERVICE_NAME: absolute-water-357521


jobs:

  build-app:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

  build-and-deploy-container:

    runs-on: ubuntu-latest

    needs: build-app

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chessplusplus-ui:$(date +%s)
    - name: Setup gcloud Auth
      uses: google-github-actions/auth@v0.8.0
      with:
        credentials_json: ${{ secrets.GCR_SA_KEY }}
    - name: Setup gcloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.0
    - name: Build and Push
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
      working-directory: .
    - name: Deploy to GCR
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
        --quiet \
        --region "$RUN_REGION" \
        --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
        --platform "managed" \
        --min-instances=1 \
        --allow-unauthenticated

